/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.qi.edu.view;

import br.qi.edu.model.Person;
import java.awt.event.KeyEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Alunos
 */
public class UIAddPerson extends javax.swing.JInternalFrame {

    /**
     * Creates new form UIAddPerson
     */
    public UIAddPerson() {
        initComponents();
    }
    
    
    
    public void insertPerson(Person person){
        Person listPerson = person;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgIsEmployee = new javax.swing.ButtonGroup();
        jlpData = new javax.swing.JLayeredPane();
        jlName = new javax.swing.JLabel();
        jlLastName = new javax.swing.JLabel();
        jsAge = new javax.swing.JSpinner();
        jlAge = new javax.swing.JLabel();
        jlIsEmployee = new javax.swing.JLabel();
        jrbYes = new javax.swing.JRadioButton();
        jrbNo = new javax.swing.JRadioButton();
        jtName = new javax.swing.JTextField();
        jtLastName = new javax.swing.JTextField();
        jlpActions = new javax.swing.JLayeredPane();
        jbAdd = new javax.swing.JButton();
        jbClean = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);

        jlpData.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados "));

        jlName.setText("Nome");

        jlLastName.setText("Ultimo sobrenome");

        jsAge.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jsAgeStateChanged(evt);
            }
        });
        jsAge.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jsAgeKeyPressed(evt);
            }
        });

        jlAge.setText("Idade");

        jlIsEmployee.setText("É um funcionário?");

        bgIsEmployee.add(jrbYes);
        jrbYes.setText("Sim");
        jrbYes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrbYesKeyPressed(evt);
            }
        });

        bgIsEmployee.add(jrbNo);
        jrbNo.setText("Não");
        jrbNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrbNoKeyPressed(evt);
            }
        });

        jtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtNameKeyPressed(evt);
            }
        });

        jtLastName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtLastNameKeyPressed(evt);
            }
        });

        jlpData.setLayer(jlName, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpData.setLayer(jlLastName, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpData.setLayer(jsAge, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpData.setLayer(jlAge, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpData.setLayer(jlIsEmployee, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpData.setLayer(jrbYes, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpData.setLayer(jrbNo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpData.setLayer(jtName, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpData.setLayer(jtLastName, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jlpDataLayout = new javax.swing.GroupLayout(jlpData);
        jlpData.setLayout(jlpDataLayout);
        jlpDataLayout.setHorizontalGroup(
            jlpDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpDataLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jlpDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlAge)
                    .addComponent(jlName))
                .addGap(28, 28, 28)
                .addGroup(jlpDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtName, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jsAge, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jlpDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlLastName)
                    .addComponent(jlIsEmployee))
                .addGroup(jlpDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jlpDataLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jrbYes)
                        .addGap(26, 26, 26)
                        .addComponent(jrbNo)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jlpDataLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jtLastName)))
                .addContainerGap())
        );
        jlpDataLayout.setVerticalGroup(
            jlpDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpDataLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jlpDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlName)
                    .addComponent(jlLastName)
                    .addComponent(jtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jlpDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jsAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlAge)
                    .addComponent(jlIsEmployee)
                    .addComponent(jrbYes)
                    .addComponent(jrbNo))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jlpActions.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jbAdd.setText("Cadastrar");
        jbAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAddActionPerformed(evt);
            }
        });
        jbAdd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbAddKeyPressed(evt);
            }
        });

        jbClean.setText("Limpar");

        jlpActions.setLayer(jbAdd, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpActions.setLayer(jbClean, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jlpActionsLayout = new javax.swing.GroupLayout(jlpActions);
        jlpActions.setLayout(jlpActionsLayout);
        jlpActionsLayout.setHorizontalGroup(
            jlpActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpActionsLayout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(jbAdd)
                .addGap(101, 101, 101)
                .addComponent(jbClean, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jlpActionsLayout.setVerticalGroup(
            jlpActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpActionsLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jlpActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAdd)
                    .addComponent(jbClean))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlpData)
                    .addComponent(jlpActions))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlpData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlpActions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void add() {
        try {
            Person person = new Person(jtName.getText(),jtLastName.getText(),jrbYes.isSelected(),Integer.parseInt(jsAge.getValue().toString()));
            JOptionPane.showMessageDialog(this,person.toString(),"Relatório",JOptionPane.PLAIN_MESSAGE);
            insertPerson(person);
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(this,"Erro: " + e.getMessage(),"ERROR",JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"Erro: " + e.getMessage(),"ERROR",JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void clean() {
        jtName.setText("");
        jtLastName.setText("");
        jsAge.setValue(0);
        bgIsEmployee.clearSelection();
        jtName.grabFocus();
    }
    private void jbAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAddActionPerformed
        add();
        clean();
    }//GEN-LAST:event_jbAddActionPerformed

    private void jsAgeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jsAgeStateChanged
        if ((int) jsAge.getValue() < 0){
            JOptionPane.showMessageDialog(this,"Selecione uma idade válida!","Idade inválida",JOptionPane.PLAIN_MESSAGE);
            jsAge.setValue(0);
        }
    }//GEN-LAST:event_jsAgeStateChanged

    private void jbAddKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbAddKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            add();
            clean();
        }
    }//GEN-LAST:event_jbAddKeyPressed

    private void jtNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtNameKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
            jtLastName.grabFocus();
    }//GEN-LAST:event_jtNameKeyPressed

    private void jtLastNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtLastNameKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
            jsAge.grabFocus();
    }//GEN-LAST:event_jtLastNameKeyPressed

    private void jsAgeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jsAgeKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
            jrbYes.grabFocus();
    }//GEN-LAST:event_jsAgeKeyPressed

    private void jrbYesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrbYesKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
            jrbNo.grabFocus();
    }//GEN-LAST:event_jrbYesKeyPressed

    private void jrbNoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrbNoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            add();
            clean();
        }
    }//GEN-LAST:event_jrbNoKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgIsEmployee;
    private javax.swing.JButton jbAdd;
    private javax.swing.JButton jbClean;
    private javax.swing.JLabel jlAge;
    private javax.swing.JLabel jlIsEmployee;
    private javax.swing.JLabel jlLastName;
    private javax.swing.JLabel jlName;
    private javax.swing.JLayeredPane jlpActions;
    private javax.swing.JLayeredPane jlpData;
    private javax.swing.JRadioButton jrbNo;
    private javax.swing.JRadioButton jrbYes;
    private javax.swing.JSpinner jsAge;
    private javax.swing.JTextField jtLastName;
    private javax.swing.JTextField jtName;
    // End of variables declaration//GEN-END:variables
}
