/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.qi.view;

import br.edu.qi.model.Student;
import com.sun.glass.events.KeyEvent;
import java.util.ArrayList;

/**
 *
 * @author Rafael & Carlos
 * @since 23/05/19 - 14:09
 * @version 1.0 Beta
 */
public class UiAddStudent extends javax.swing.JFrame {

    /**
     * Creates new form UiAddStudent
     */
    public UiAddStudent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgGender = new javax.swing.ButtonGroup();
        jlpData = new javax.swing.JLayeredPane();
        jlName = new javax.swing.JLabel();
        jlGrade1 = new javax.swing.JLabel();
        jlGrade2 = new javax.swing.JLabel();
        jlClassTotal = new javax.swing.JLabel();
        jlAttendance = new javax.swing.JLabel();
        jlSubject = new javax.swing.JLabel();
        jlGender = new javax.swing.JLabel();
        jrMale = new javax.swing.JRadioButton();
        jrFemale = new javax.swing.JRadioButton();
        jtName = new javax.swing.JTextField();
        jtGrade1 = new javax.swing.JTextField();
        jtGrade2 = new javax.swing.JTextField();
        jtClassTotal = new javax.swing.JTextField();
        jtAttendance = new javax.swing.JTextField();
        jcLanguageProgramVisual = new javax.swing.JCheckBox();
        jcLanguageProgramWeb = new javax.swing.JCheckBox();
        jcLogic = new javax.swing.JCheckBox();
        jcDataBase = new javax.swing.JCheckBox();
        jsAnswer = new javax.swing.JScrollPane();
        jtaAnswer = new javax.swing.JTextArea();
        jlWeight1 = new javax.swing.JLabel();
        jlWeight2 = new javax.swing.JLabel();
        jtWeight1 = new javax.swing.JTextField();
        jtWeight2 = new javax.swing.JTextField();
        jlpActions = new javax.swing.JLayeredPane();
        jbAdd = new javax.swing.JButton();
        jbClean = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlpData.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jlName.setText("Nome");

        jlGrade1.setText("Nota 1");

        jlGrade2.setText("Nota 2");

        jlClassTotal.setText("Total de Aulas");

        jlAttendance.setText("Número de Presenças");

        jlSubject.setText("Disciplinas");

        jlGender.setText("Sexo");

        bgGender.add(jrMale);
        jrMale.setText("Masculino");
        jrMale.setActionCommand("Masculino");
        jrMale.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrMaleKeyPressed(evt);
            }
        });

        bgGender.add(jrFemale);
        jrFemale.setText("Feminino");
        jrFemale.setActionCommand("Feminino");
        jrFemale.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrFemaleKeyPressed(evt);
            }
        });

        jtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtNameKeyPressed(evt);
            }
        });

        jtGrade1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtGrade1KeyPressed(evt);
            }
        });

        jtGrade2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtGrade2KeyPressed(evt);
            }
        });

        jtClassTotal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtClassTotalKeyPressed(evt);
            }
        });

        jtAttendance.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtAttendanceKeyPressed(evt);
            }
        });

        jcLanguageProgramVisual.setText("Linguagem Programação Visual");
        jcLanguageProgramVisual.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jcLanguageProgramVisualKeyPressed(evt);
            }
        });

        jcLanguageProgramWeb.setText("Linguagem de programação Web");
        jcLanguageProgramWeb.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jcLanguageProgramWebKeyPressed(evt);
            }
        });

        jcLogic.setText("Lógica");
        jcLogic.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jcLogicKeyPressed(evt);
            }
        });

        jcDataBase.setText("BD1");
        jcDataBase.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jcDataBaseKeyPressed(evt);
            }
        });

        jsAnswer.setFocusable(false);

        jtaAnswer.setColumns(20);
        jtaAnswer.setRows(5);
        jtaAnswer.setFocusable(false);
        jsAnswer.setViewportView(jtaAnswer);

        jlWeight1.setText("Peso 1");

        jlWeight2.setText("Peso 2");

        jtWeight1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtWeight1KeyPressed(evt);
            }
        });

        jtWeight2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtWeight2KeyPressed(evt);
            }
        });

        jlpData.setLayer(jlName, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpData.setLayer(jlGrade1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpData.setLayer(jlGrade2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpData.setLayer(jlClassTotal, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpData.setLayer(jlAttendance, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpData.setLayer(jlSubject, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpData.setLayer(jlGender, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpData.setLayer(jrMale, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpData.setLayer(jrFemale, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpData.setLayer(jtName, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpData.setLayer(jtGrade1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpData.setLayer(jtGrade2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpData.setLayer(jtClassTotal, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpData.setLayer(jtAttendance, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpData.setLayer(jcLanguageProgramVisual, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpData.setLayer(jcLanguageProgramWeb, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpData.setLayer(jcLogic, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpData.setLayer(jcDataBase, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpData.setLayer(jsAnswer, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpData.setLayer(jlWeight1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpData.setLayer(jlWeight2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpData.setLayer(jtWeight1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpData.setLayer(jtWeight2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jlpDataLayout = new javax.swing.GroupLayout(jlpData);
        jlpData.setLayout(jlpDataLayout);
        jlpDataLayout.setHorizontalGroup(
            jlpDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpDataLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jlpDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jlpDataLayout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addComponent(jsAnswer, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jlpDataLayout.createSequentialGroup()
                        .addGroup(jlpDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jlpDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jlpDataLayout.createSequentialGroup()
                                    .addComponent(jlAttendance)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jtAttendance))
                                .addGroup(jlpDataLayout.createSequentialGroup()
                                    .addComponent(jlClassTotal)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jtClassTotal))
                                .addGroup(jlpDataLayout.createSequentialGroup()
                                    .addComponent(jlGrade2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jtGrade2))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jlpDataLayout.createSequentialGroup()
                                    .addComponent(jlName)
                                    .addGap(18, 18, 18)
                                    .addComponent(jtName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jlpDataLayout.createSequentialGroup()
                                    .addComponent(jlGrade1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jtGrade1)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jlpDataLayout.createSequentialGroup()
                                .addComponent(jlSubject)
                                .addGap(18, 18, 18)
                                .addGroup(jlpDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jcLanguageProgramWeb)
                                    .addComponent(jcLogic)
                                    .addGroup(jlpDataLayout.createSequentialGroup()
                                        .addGroup(jlpDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jlGender)
                                            .addComponent(jcLanguageProgramVisual)
                                            .addComponent(jcDataBase, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGroup(jlpDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jlpDataLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jrMale)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jrFemale))
                                            .addGroup(jlpDataLayout.createSequentialGroup()
                                                .addGap(86, 86, 86)
                                                .addGroup(jlpDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jlWeight1)
                                                    .addComponent(jlWeight2))
                                                .addGap(33, 33, 33)
                                                .addGroup(jlpDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jtWeight1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jtWeight2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGap(38, 38, 38))
        );
        jlpDataLayout.setVerticalGroup(
            jlpDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpDataLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jlpDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlName)
                    .addComponent(jlGender)
                    .addComponent(jtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jrMale)
                    .addComponent(jrFemale))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jlpDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jlpDataLayout.createSequentialGroup()
                        .addGroup(jlpDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlGrade1)
                            .addComponent(jtGrade1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jlpDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlGrade2)
                            .addComponent(jtGrade2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jlpDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlClassTotal)
                            .addComponent(jtClassTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jlpDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlAttendance)
                            .addComponent(jtAttendance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jsAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jcLanguageProgramVisual)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jlpDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlSubject)
                    .addGroup(jlpDataLayout.createSequentialGroup()
                        .addComponent(jcLanguageProgramWeb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcLogic)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcDataBase))
                    .addGroup(jlpDataLayout.createSequentialGroup()
                        .addGroup(jlpDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlWeight1)
                            .addComponent(jtWeight1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jlpDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlWeight2)
                            .addComponent(jtWeight2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jlpActions.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jlpActions.setToolTipText("");

        jbAdd.setText("Cadastrar");
        jbAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAddActionPerformed(evt);
            }
        });

        jbClean.setText("Limpar");
        jbClean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCleanActionPerformed(evt);
            }
        });

        jlpActions.setLayer(jbAdd, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpActions.setLayer(jbClean, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jlpActionsLayout = new javax.swing.GroupLayout(jlpActions);
        jlpActions.setLayout(jlpActionsLayout);
        jlpActionsLayout.setHorizontalGroup(
            jlpActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jlpActionsLayout.createSequentialGroup()
                .addGap(229, 229, 229)
                .addComponent(jbAdd)
                .addGap(51, 51, 51)
                .addComponent(jbClean)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jlpActionsLayout.setVerticalGroup(
            jlpActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jlpActionsLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(jlpActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAdd)
                    .addComponent(jbClean))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlpData)
                    .addComponent(jlpActions))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlpData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlpActions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void add() {
        
        ArrayList <String> discipline = new ArrayList<>();
        
        if (jcLanguageProgramVisual.isSelected())
            discipline.add(jcLanguageProgramVisual.getText());
        
        if (jcLanguageProgramWeb.isSelected())
            discipline.add(jcLanguageProgramWeb.getText());
        
        if (jcLogic.isSelected())
            discipline.add(jcLogic.getText());
        
        if (jcDataBase.isSelected())
            discipline.add(jcDataBase.getText());

        Student student = new Student(jtName.getText(),
                                      Double.parseDouble(jtGrade1.getText()),
                                      Double.parseDouble(jtGrade2.getText()),
                                      Integer.parseInt(jtClassTotal.getText()),
                                      Integer.parseInt(jtAttendance.getText()),
                                      bgGender.getSelection().getActionCommand(),
                                      discipline,
                                      Integer.parseInt(jtWeight1.getText()),
                                      Integer.parseInt(jtWeight2.getText()));
        
        jtaAnswer.setText("Relatório\n"+student.toString());
    }
    
    private void clean() {
        jtAttendance.setText("");
        jtClassTotal.setText("");
        jtGrade1.setText("");
        jtGrade2.setText("");
        jtName.setText("");
        jtWeight1.setText("");
        jtWeight2.setText("");
        bgGender.clearSelection();
        jcDataBase.setSelected(false);
        jcLanguageProgramVisual.setSelected(false);
        jcLanguageProgramWeb.setSelected(false);
        jcLogic.setSelected(false);
    }
    
    private void jbAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAddActionPerformed
        add();
        clean();
        jtName.grabFocus();
    }//GEN-LAST:event_jbAddActionPerformed

    private void jbCleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCleanActionPerformed
        clean();
        jtName.grabFocus();
    }//GEN-LAST:event_jbCleanActionPerformed

    private void jtNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtNameKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
            jtGrade1.grabFocus();
    }//GEN-LAST:event_jtNameKeyPressed

    private void jtGrade1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtGrade1KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
            jtGrade2.grabFocus();
    }//GEN-LAST:event_jtGrade1KeyPressed

    private void jtGrade2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtGrade2KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtClassTotal.grabFocus();
        }
    }//GEN-LAST:event_jtGrade2KeyPressed

    private void jtClassTotalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtClassTotalKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
            jtAttendance.grabFocus();
    }//GEN-LAST:event_jtClassTotalKeyPressed

    private void jtAttendanceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtAttendanceKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jcLanguageProgramVisual.grabFocus();
        }
    }//GEN-LAST:event_jtAttendanceKeyPressed

    private void jcLanguageProgramVisualKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcLanguageProgramVisualKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
            jcLanguageProgramWeb.grabFocus();
    }//GEN-LAST:event_jcLanguageProgramVisualKeyPressed

    private void jcLanguageProgramWebKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcLanguageProgramWebKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
            jcLogic.grabFocus();
    }//GEN-LAST:event_jcLanguageProgramWebKeyPressed

    private void jcLogicKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcLogicKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
            jcDataBase.grabFocus();
    }//GEN-LAST:event_jcLogicKeyPressed

    private void jcDataBaseKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcDataBaseKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
            jtWeight1.grabFocus();
    }//GEN-LAST:event_jcDataBaseKeyPressed

    private void jtWeight1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtWeight1KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
            jtWeight2.grabFocus();
        
    }//GEN-LAST:event_jtWeight1KeyPressed

    private void jtWeight2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtWeight2KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
            jrMale.grabFocus();
    }//GEN-LAST:event_jtWeight2KeyPressed

    private void jrMaleKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrMaleKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
            jrFemale.grabFocus();
    }//GEN-LAST:event_jrMaleKeyPressed

    private void jrFemaleKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrFemaleKeyPressed
       if (evt.getKeyCode() == KeyEvent.VK_ENTER){
           add();
           clean();
           jtName.grabFocus();
       }
    }//GEN-LAST:event_jrFemaleKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UiAddStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UiAddStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UiAddStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UiAddStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UiAddStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgGender;
    private javax.swing.JButton jbAdd;
    private javax.swing.JButton jbClean;
    private javax.swing.JCheckBox jcDataBase;
    private javax.swing.JCheckBox jcLanguageProgramVisual;
    private javax.swing.JCheckBox jcLanguageProgramWeb;
    private javax.swing.JCheckBox jcLogic;
    private javax.swing.JLabel jlAttendance;
    private javax.swing.JLabel jlClassTotal;
    private javax.swing.JLabel jlGender;
    private javax.swing.JLabel jlGrade1;
    private javax.swing.JLabel jlGrade2;
    private javax.swing.JLabel jlName;
    private javax.swing.JLabel jlSubject;
    private javax.swing.JLabel jlWeight1;
    private javax.swing.JLabel jlWeight2;
    private javax.swing.JLayeredPane jlpActions;
    private javax.swing.JLayeredPane jlpData;
    private javax.swing.JRadioButton jrFemale;
    private javax.swing.JRadioButton jrMale;
    private javax.swing.JScrollPane jsAnswer;
    private javax.swing.JTextField jtAttendance;
    private javax.swing.JTextField jtClassTotal;
    private javax.swing.JTextField jtGrade1;
    private javax.swing.JTextField jtGrade2;
    private javax.swing.JTextField jtName;
    private javax.swing.JTextField jtWeight1;
    private javax.swing.JTextField jtWeight2;
    private javax.swing.JTextArea jtaAnswer;
    // End of variables declaration//GEN-END:variables
}
